FROM mcr.microsoft.com/dotnet/aspnet:9.0-noble-chiseled AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/ActiveDirectoryWebFrontend/ActiveDirectoryWebFrontend.csproj", "src/ActiveDirectoryWebFrontend/"]
RUN dotnet restore "./src/ActiveDirectoryWebFrontend/ActiveDirectoryWebFrontend.csproj"
COPY . .
WORKDIR "/src/src/ActiveDirectoryWebFrontend"
RUN dotnet build "./ActiveDirectoryWebFrontend.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ActiveDirectoryWebFrontend.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ActiveDirectoryWebFrontend.dll"]
